#!/usr/bin/env bash

echo "\n==================== pre-push hook ===================="

# Export conda environment to yaml file
conda env export -n sbac > conda_env.yml

# Check if new environment file is different from original 
git diff --exit-code --quiet conda_env.yml 

# If new environment file is different, commit it
if [[ $? -eq 0 ]]; then
    echo "Conda environment not changed. No additional commit."
else
    echo "Conda environment changed. Commiting new conda_env.yml"
    git add conda_env.yml
    git commit -m "Updating conda environment"
    echo 'You need to push again to push additional "Updating conda environment" commit.'
    exit 1
fi
